version: "3.10"
services:
  voting:
    build: .
    env_file: .env
    depends_on:
        redis:
          condition: service_healthy
    command: python3 -m voting.api
    ports:
      - "8000:8000"
  redis:
    image: redis
    command: redis-server --save 60 10
    volumes:
      - redis_persistent_data:/data/:delegated
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 3

volumes:
  redis_persistent_data:
