version: "3.10"
services:
  webapp:
    build: .
    env_file: .env
    depends_on:
        redis:
          condition: service_healthy
    ports:
      - "8000:8000"
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 3
